name: step_progress
description: A lightweight package for displaying customizable step progress indicators in a user interface.
version: 1.0.4
homepage: https://github.com/TalebRafiepour/step-progress
issue_tracker: https://github.com/TalebRafiepour/step-progress/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
