name: step_progress
description: A progress widget for showing proccess completed step by step.
version: 0.0.1
author: Taleb Rafiepour <taleb.r75@gmail.com>
homepage: https://github.com/TalebRafiepour/step-progress.git
issue_tracker: https://github.com/TalebRafiepour/step-progress/issues

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
