name: step_progress
description: A lightweight package for displaying customizable step progress indicators in a user interface.
version: 2.0.1
homepage: https://github.com/TalebRafiepour/step-progress
issue_tracker: https://github.com/TalebRafiepour/step-progress/issues

topics: 
  - stepper
  - stepprogress
  - progressindicator
  - stepbystep
  - steptracker

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
