name: Code Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get packages
        run: flutter pub get
      - name: Generate coverage file
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TalebRafiepour/step_progress
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: flutter